#!/bin/bash
#  SPDX-License-Identifier: GPL-2.0

# Running this script will copy the modules from
# the in-memory tmpfs filesystem on the root filesystem,
# and arrange that the tmpfs filesystem is not used in
# future reboots.

keep() {
    mkdir /tmp/modules
    mount --bind /lib/modules /tmp/modules
    umount -l /lib/modules
    r=`uname -r`
    echo Copying modules to /lib/modules/$r
    rm -rf /mnt/root/lib/modules/$r
    cp -a /tmp/modules/. /lib/modules
    rm -f /lib/modules/keep # don't need that any more
    rm -fr /tmp/modules/*
    umount /tmp/modules
    rmdir /tmp/modules
    echo /lib/modules/$r installed from boot image.
}

keep
