#!/bin/sh

if /sbin/swconfig list | grep switch0 > /dev/null
then # there is a switch
  exit 1
fi
if [ -d /sys/class/net/eth0/dsa ]; then
    # we have DSA support, which enables the switch
    exit 1
fi
exit 0
