#!/bin/sh

if /sbin/swconfig list | grep switch0 > /dev/null
then # there is a switch
      swconfig dev switch0 set reset
      swconfig dev switch0 set enable_vlan 1
      swconfig dev switch0 vlan 1 set ports '0 6t'
      swconfig dev switch0 vlan 2 set ports '4 6t'
      swconfig dev switch0 port 0 set pvid 1
      swconfig dev switch0 port 4 set pvid 2
      swconfig dev switch0 set apply

      exit 0
fi
exit 1
